POKEMON["Pichu"] = {
    pTypes = { ELEMENT_ELECTRIC },
    dexStorage = 10172,
    atk = 40,
    def = 15,
    spAtk = 35,
    spDef = 35,
    energy = 100,
    chance = 80,
    portrait = 17461,
    dexPortrait = 15819,
    fastcallPortrait = 16019,
    weight = 20,
	catchStorage = 16172,
    evolutions = { { name = "Pikachu", requiredLevel = 1, requiredHappiness = HAPPINESS_HIGH } },
    description = "Despite its small size, it can zap even adult humans. However, if it does so, it also surprises itself.",
    skills = { "Thunder Shock", 1, "Swift", 5, "Double Team", 10, "Electro Ball", 15, "Agility", 20, "Thunderbolt", 25, "Nasty Plot", 30, "Discharge", 35 },
    abilities = { "Flash", "Headbutt" },
    eggGroup = {},
    eggId = 13987,
    eggChance = 0,
    moveTutor = {
        {"Charge", 15, ELEMENT_ELECTRIC},
        {"Electric Terrain", 10, ELEMENT_ELECTRIC},
        {"Shock Wave", 10, ELEMENT_ELECTRIC},
        {"Zap Cannon", 10, ELEMENT_ELECTRIC},
        {"Volt Switch", 10, ELEMENT_ELECTRIC},
        {"Volt Tackle", 10, ELEMENT_ELECTRIC},
    },
    specialAbilities = { POKEMON_SPECIAL_ABILITY_IDS.STATIC },
    hiddenAbility = POKEMON_SPECIAL_ABILITY_IDS.LIGHTNINGROD,
    learnableTms = { TM_IDS.MAGNET_RISE, TM_IDS.NASTY_PLOT, TM_IDS.ELETRIC_TERRAIN, TM_IDS.WILD_CHARGE, TM_IDS.GRASS_KNOT, TM_IDS.CHARGE_BEAM, TM_IDS.ECHOED_VOICE, TM_IDS.DEFENSE_CURL, TM_IDS.MUD_SLAP, TM_IDS.IRON_TAIL, TM_IDS.RAIN_DANCE, TM_IDS.ZAP_CANNON, TM_IDS.HEADBUTT, TM_IDS.THUNDER_WAVE, TM_IDS.SWIFT, TM_IDS.TOXIC, TM_IDS.DOUBLE_EDGE, TM_IDS.RAGE, TM_IDS.THUNDERBOLT, TM_IDS.THUNDER, TM_IDS.MIMIC, TM_IDS.DOUBLE_TEAM, TM_IDS.REST, TM_IDS.BIDE, TM_IDS.SUBSTITUTE, },
    learnableHms = { HM_IDS.SURF },
    eggMoves = { "Bide", "Disarming Voice", "Double Slap", "Encore", "Endure", "Fake Out", "Flail", "Lucky Chant", "Present","Thunder Punch", "Tickle" }
}